#!/bin/bash  

xcodebuild archive \
  -scheme mobdebug \
  -destination "generic/platform=iOS" \
  -archivePath ./build/ios_devices.xcarchive \
  SKIP_INSTALL=NO \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES


xcodebuild archive \
  -scheme mobdebug \
  -destination "generic/platform=iOS Simulator" \
  -archivePath ./build/ios_sim.xcarchive \
  SKIP_INSTALL=NO \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES

