#!/bin/bash

xcodebuild -create-xcframework \
  -framework ./build/ios_devices.xcarchive/Products/Library/Frameworks/mobdebug.framework \
  -framework ./build/ios_sim.xcarchive/Products/Library/Frameworks/mobdebug.framework \
  -output ./mobdebug.xcframework
