#!/bin/bash

WAX_FRAMEWORK_DIR="../../framework"
rm -rf "$WAX_FRAMEWORK_DIR/wax.xcframework"

xcodebuild -create-xcframework \
  -framework ./build/ios_devices.xcarchive/Products/Library/Frameworks/wax.framework \
  -framework ./build/ios_sim.xcarchive/Products/Library/Frameworks/wax.framework \
  -output "$WAX_FRAMEWORK_DIR/wax.xcframework"
