platform :ios

target 'States' do
  platform:ios, '15.0'
  pod 'wax', :path=>'../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'wax'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
      end
    end
  end
end
